version: "3.9"

services:
  node-app:
    build: .
    depends_on:
      - postgres-db
      - redis-db
    networks:
      - data

  postgres-db:
    restart: always
    container_name: postgres-db
    image: postgres:17.5
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    #ports:
    #  - "${POSTGRES_CLIENT_PORT}:${POSTGRES_PORT}"
    #expose:
    #  - "${POSTGRES_PORT}"
    networks:
      - data
    tty: true

  redis-db:
    restart: always
    container_name: "redis-db"
    image: "redis:7.4.4-alpine"
    depends_on:
      - "postgres-db"
    #ports:
    #  - "${REDIS_PORT}:${REDIS_PORT}"
    #expose:
    #  - "${REDIS_PORT}"
    volumes:
      - "redis-data:/data"
    networks:
      - data

volumes:
  pg-data: ~
  redis-data: ~

networks:
  data:
    driver: bridge
